// @ts-check
// Flat config — extends the config generated by the @nuxt/eslint module.
// The module writes .nuxt/eslint.config.mjs during `nuxt prepare`, wiring up
// Vue + TS rules tuned for this project's structure (app/, server/).
import withNuxt from './.nuxt/eslint.config.mjs'

export default withNuxt(
  {
    rules: {
      // Allow single-word component/page names (auth.vue, index.vue) — Nuxt
      // file-based routing relies on these.
      'vue/multi-word-component-names': 'off',
    },
  },
  {
    // Test files: `any` is acceptable for mock/stub typing and fake-db
    // harnesses, where modelling the full runtime types adds noise without
    // catching real bugs.
    files: ['tests/**/*.ts', '**/*.test.ts'],
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
    },
  },
)
